apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment # กำหนด label ของ deployment
spec:
  replicas: 2
  selector:
    matchLabels: # กำหนด label ของ pod ที่จะดูแล
      app: nginx-app
  template: # กำหนด template spec ของ pod ที่จะดูแล
    metadata:
      labels:
        app: nginx-app
    spec:
      containers: # docker image ที่จะใช้งาน
        - name: nginx-app # กำหนดชื่อของ container
          image: nginx:1.14.2
          ports:
            - containerPort: 80 # กำหนด port ของ container